image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  SECURE_LOG_LEVEL: info
  DS_JAVA_VERSION: 11
  DOCKER_DRIVER: overlay
  CONTAINER_IMAGE: smartcommunitylab/playngo-hsc:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
  CONTAINER_IMAGE_LATEST: smartcommunitylab/playngo-hsc:$CI_COMMIT_REF_NAME-latest
  CONTAINER_CACHE_IMAGE: smartcommunitylab/playngo-hsc:cache
  SAST_JAVA_VERSION: 11

include:
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml

update-backend-cache-image:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -f Dockerfile-cache -t $CONTAINER_CACHE_IMAGE .
    - docker push $CONTAINER_CACHE_IMAGE
  rules:
    - changes:
      - pom.xml

maven-build:
  image: maven:3-openjdk-11
  stage: build
  script:
    - mvn -DskipTests=true clean package
  only:
    - main

gemnasium-maven-dependency_scanning:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

semgrep-sast:
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

container_scanning:
  stage: test
  dependencies:
    - backend-container-build
  variables:
    DOCKER_IMAGE: smartcommunitylab/playngo-hsc:$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA
    DOCKERFILE_PATH: "Dockerfile"
    GIT_STRATEGY: fetch
    DOCKER_USER: ""
    DOCKER_PASSWORD: ""
    CS_IMAGE: smartcommunitylab/playngo-hsc:$CI_COMMIT_REF_NAME-latest
  rules:
     - if: '$CI_COMMIT_REF_NAME == "main"'

backend-container-build:
  stage: build
  variables:
    BUILDKIT_PROGRESS: plain
    DOCKER_BUILDKIT: 1 
  script:
    - docker login -u $DHUB_USER -p $DHUB_PASS
    - docker build -f Dockerfile --build-arg VER=1.0 -t $CONTAINER_IMAGE -t $CONTAINER_IMAGE_LATEST .
    - docker push $CONTAINER_IMAGE
    - docker push $CONTAINER_IMAGE_LATEST
  only:
    - dev
    - prod
    - main

deploy-dev:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy backend"
    - kubectl -n playngo-dev set image deployments/playngo-hsc playngo-hsc=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-dev rollout status deployment playngo-hsc
  only:
    - dev

deploy-prod:
  stage: deploy
  image: 
    name: bitnami/kubectl:latest
    entrypoint: ['']
  environment:
    name: dslab
  script:
    - echo "deploy backend"
    - kubectl -n playngo-prod set image deployments/playngo-hsc playngo-hsc=$CONTAINER_IMAGE --record=true
    - kubectl -n playngo-prod rollout status deployment playngo-hsc
  only:
    - prod