server:
  port: 7022
  servlet:
    contextPath: /playandgo-hsc

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URL:}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  security:
    oauth2:
      client:
        registration:
          oauthprovider: 
            authorization-grant-type: client_credentials
            client-id:  ${AAC_CLIENT_ID:}
            client-secret:  ${AAC_CLIENT_SECRET:}
          aac: 
            client-id:  ${AAC_CLIENT_ID:}
            client-secret:  ${AAC_CLIENT_SECRET:}
            authorization-grant-type: authorization_code
            provider: oauthprovider
        provider:
          oauthprovider:
            token-uri: ${AAC_TOKEN_URI:}
            issuer-uri: ${AAC_ISSUER_URI:}
            authorization-uri: ${AAC_AUTHORIZATION_URI:}

playandgo:
  engine:
    uri: ${PLAYANDGO_ENGINE_URI:} 

minio:
  endpoint: ${MINIO_ENDPOINT:}
  accessKey: ${MINIO_ACCESS_KEY:}
  secretKey: ${MINIO_SECRET_KEY:}
  bucket: ${MINIO_BUCKET:}   

gamification:
  url: ${GAMIFICATION_URL:}
  user: ${GAMIFICATION_USER:}
  password: ${GAMIFICATION_PASSWORD:}
  secretKey1: ${GAMIFICATION_SK1:}
  secretKey2: ${GAMIFICATION_SK2:}     